packageExtensions:
  html-minifier-terser@*:
    dependencies:
      acorn: ^8.6.0
  terser-webpack-plugin@*:
    dependencies:
      acorn: ^8.6.0
  '@docusaurus/theme-classic@2.0.0-beta.13':
    dependencies:
      '@docusaurus/types': '2.0.0-beta.13'
  '@docusaurus/theme-live-codeblock@2.0.0-beta.13':
    dependencies:
      'tslib': '^2.3.1'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
