version: 2.1

jobs:

  build:
    docker:
      - image: circleci/node:16.4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install dependencies
          command: yarn install || true # Temporary until TS errors are fixed in Docusaurus
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Build Website
          command: yarn build

  deploy-gh-pages:
    docker:
      - image: circleci/node:16.4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install dependencies
          command: yarn install || true # Temporary until TS errors are fixed in docusaurusu
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Configure Git Credentials
          command: |
            git config --global user.email "sidachen2003@gmail.com"
            git config --global user.name "Josh-Cena"
            echo "machine github.com login Josh-Cena password $GITHUB_PA_TOKEN" > ~/.netrc
      - attach_workspace:
          at: .
      - run:
          name: Deploy to GitHub Pages
          command: yarn deploy
          # Set environment variables so that project is deployed correctly
          environment:
            GIT_USER: Josh-Cena 
            ORGANIZATION_NAME: Josh-Cena
            PROJECT_NAME: Josh-Cena.github.io
            DEPLOYMENT_BRANCH: master
            CURRENT_BRANCH: master

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy-gh-pages:
          filters:
            branches:
              only: master
